### ISSUE TITLE
Silence output

### ISSUE THREAD

**Issue by jennysjaarda** [aryoda/tryCatchLog#46]
Just wondering if there is currently (or will be in the future) a command to silence (some of) the output of PRSice? My computing cluster automatically creates out files and they are very large to the update reading updates and processing percentages, etc. 

Thanks in advance!
Jenny

**Comment by aryoda** [comment]
Jenny, which logging framework are you using with `tryCatchLog` and how do you use it together with `tryCatchLog`? Do you have a minimal reproducible code example you could post here?

The default logging functions of the `tryCatchLog` package are just stupid "print everything to console" functions without any support to change the logging verbosity (see the source code https://github.com/aryoda/tryCatchLog/blob/master/R/log2console.R).

If you are in need to change the logging verbosity you can register your own logging functions or use the package `futile.logger` which is supported out of the box and allows changing the logging verbosity with

    library(tryCatchLog)
    library(futile.logger)
    flog.threshold(ERROR)  # log only errors and above

For details on how to use `futile.logger` see
https://github.com/zatonovo/futile.logger

**Comment by jennysjaarda** [comment]
Thanks very much!
