### ISSUE TITLE
Allow access to original error message without any log output additions (timestamp)

### ISSUE THREAD

**Issue by R2Python** [aryoda/tryCatchLog#69]
When throwing an error, it would be helpful if tryCatchLog would allow access to the original message (e.g., "Invalid parameter" from stop("Invalid parameter")) without any additions (traceback, type of condition ("WARNING "/ "ERROR"), timestamp). At the moment, this would be part of a much larger error message that would have to be parsed to get to the original message. It would be nice if one could write one's own error messages to the console (which might be part of a logging of a larger system) and log a much more detailed version to a file. This would require that the error message receives too parts: 
1. the original error
2. the augmented version (with traceback, etc. as determined by include.full.call.stack and include.compact.call.stack)

For a complete example of this scenario, consult: 

https://stackoverflow.com/questions/70274274/r-errorhandling-with-trycatchlog-create-a-customizable-result-code-for-the-co

**Comment by aryoda** [comment]
There is an existing function for this:

```
tryCatchLog::tryLog({ log(-1); log("a") })
x <- tryCatchLog::last.tryCatchLog.result()
```

You will get a `data.frame` with all catched conditions and error message and call stack in separate columns:

![Screenshot from 2021-12-08 15-22-50](https://user-images.githubusercontent.com/11374410/145224572-59f18a3a-e0b3-447e-8b35-17e2217e4b8c.png)

Does this help?
