### ISSUE TITLE
Cran release

### ISSUE THREAD

**Issue by instantkaffee** [aryoda/tryCatchLog#79]
Do you still maintain and release for CRAN?

**Comment by aryoda** [comment]
Yes, I am still maintaining this R package and publish releases at CRAN.

Do you need a new feature or even an (urgent?) bug fix (not yet released)?

I am currently focusing on another project so `tryCatchLog` did not get much attention from
my side the last 12 months but the next release will be a major release with a big new feature described here:

https://github.com/aryoda/tryCatchLog/issues/71#issuecomment-1200382495

Currently the documentation for this feature is incomplete and some more tests required,
I hope to finish this soon...

**Comment by aryoda** [comment]
I am closing this issue (see kinda follow-up in #80 now)...
